
spring:
  application:
    name: consred-example
  cloud:
    consul:
      discovery:
#        healthCheckPath: ${management.server.servlet.context-path}/health
        instanceId: ${spring.application.name}:${random.value}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
server:
  port: 8080